name: rclone
version: 1.35
summary: rsync for cloud storage
description:
 Written in go with support for device auto-detection via libgudev,
 you would need to use hw-assign to access devices.
confinement: strict

apps:
  rclone:
    command: bin/rclone

parts:
  rclone:
    plugin: go
    source: https://github.com/ncw/rclone
    source-type: git
    go-importpath: github.com/ncw/rclone
    build-packages: [gcc, libgudev-1.0-dev]
