name: rclone
version: 1.35
summary: 
d"rsync for cloud storage" - Google Drive, Amazon Drive, S3, Dropbox, Backblaze B2, One Drive, Swift, Hubic, Cloudfiles, Google Cloud Storage, Yandex Files 
confinement: strict
grade: stable

apps:
  rclone:
    command: /usr/sbin/rclone

parts:
  rclone:
    plugin: go
    source: https://github.com/ncw/rclone
    source-type: git
    go-importpath: github.com/ncw/rclone
    
